import type { EventInput } from "./types";

type SeedEvent = EventInput & { slug: string };

const standardTickets = [
  { label: "PayPal", url: "https://example.com/checkout/paypal" },
  { label: "Stripe", url: "https://example.com/checkout/stripe" },
];

const meetGreetTickets = [
  { label: "Photo op · PayPal", url: "https://example.com/checkout/photo-paypal" },
  { label: "Photo op · Stripe", url: "https://example.com/checkout/photo-stripe" },
  { label: "Autograph · Stripe", url: "https://example.com/checkout/autograph" },
];

export const seedEvents: SeedEvent[] = [
  {
    slug: "fancloud-los-angeles-2026",
    title: "FanCloud Los Angeles",
    city: "Los Angeles",
    venue: "Los Angeles Convention Center",
    country: "USA",
    startDate: "2026-07-10",
    endDate: "2026-07-12",
    category: "Comic Con",
    eventType: "convention",
    color: "#6d5efc",
    heroImage: null,
    attendance: 95000,
    description:
      "Three days of A-list reunions, photo ops, and live Q&A panels in downtown LA. Expect cast members from the biggest film and streaming franchises of the year, plus exclusive autograph sessions you won't get anywhere else.",
    ticketUrl: null,
    ticketOptions: standardTickets,
    celebrityName: null,
    celebrityBio: null,
    celebrityImage: null,
    featured: true,
    status: "upcoming",
  },
  {
    slug: "fancloud-new-york-2026",
    title: "FanCloud New York",
    city: "New York",
    venue: "Javits Center",
    country: "USA",
    startDate: "2026-10-08",
    endDate: "2026-10-11",
    category: "Comic Con",
    eventType: "convention",
    color: "#16a34a",
    heroImage: null,
    attendance: 180000,
    description:
      "Our flagship east-coast show packs four days of celebrity panels, autograph sessions, and exclusive photo ops with stars from film, TV, and animation. The biggest celebrity lineup on the calendar.",
    ticketUrl: null,
    ticketOptions: standardTickets,
    celebrityName: null,
    celebrityBio: null,
    celebrityImage: null,
    featured: true,
    status: "upcoming",
  },
  {
    slug: "fancloud-tokyo-anime-fest-2026",
    title: "FanCloud Tokyo Anime Fest",
    city: "Tokyo",
    venue: "Tokyo Big Sight",
    country: "Japan",
    startDate: "2026-08-21",
    endDate: "2026-08-23",
    category: "Anime",
    eventType: "convention",
    color: "#ec4899",
    heroImage: null,
    attendance: 120000,
    description:
      "Voice-actor stages, mangaka signings, and studio Q&As with the people behind your favorite anime. The largest international voice-talent lineup of the year, plus rare on-stage interviews and exclusive autograph sessions.",
    ticketUrl: null,
    ticketOptions: standardTickets,
    celebrityName: null,
    celebrityBio: null,
    celebrityImage: null,
    featured: true,
    status: "upcoming",
  },
  {
    slug: "stranger-things-cast-meet-greet-chicago",
    title: "Stranger Things — Cast Meet & Greet",
    city: "Chicago",
    venue: "Navy Pier Grand Ballroom",
    country: "USA",
    startDate: "2026-08-15",
    endDate: "2026-08-15",
    category: "Sci-Fi",
    eventType: "meet_greet",
    color: "#dc2626",
    heroImage: null,
    attendance: 2000,
    description:
      "A single-day, intimate meet & greet with cast members from one of the most-loved sci-fi series of the decade. Limited photo ops, signed merch packages, and a live audience Q&A — capped strictly at 2,000 fans so every ticket really means something.",
    ticketUrl: null,
    ticketOptions: meetGreetTickets,
    celebrityName: "Stranger Things cast",
    celebrityBio:
      "Confirmed guests include several of the principal cast from the series. Specific names announced 30 days before the event. All photo ops are professionally lit, hosted, and capped — no chaotic lines.",
    celebrityImage: null,
    featured: true,
    status: "upcoming",
  },
  {
    slug: "voice-of-anime-tour-2026",
    title: "Voice of Anime — North American Tour",
    city: "Multiple cities",
    venue: "See city dates",
    country: "USA",
    startDate: "2026-09-12",
    endDate: "2026-10-18",
    category: "Anime",
    eventType: "tour",
    color: "#a855f7",
    heroImage: null,
    attendance: null,
    description:
      "Eight cities, four English-language voice-acting legends, one tour. Each stop includes a live recreated script reading, an audience Q&A, and a meet & greet with all four guests. Tour cities: LA, San Francisco, Seattle, Denver, Chicago, Toronto, Boston, NYC.",
    ticketUrl: null,
    ticketOptions: standardTickets,
    celebrityName: "Featured voice cast",
    celebrityBio:
      "A rotating lineup of four English-dub voice actors with combined credits on more than 200 anime series. Full lineup posted on the tour landing page.",
    celebrityImage: null,
    featured: false,
    status: "upcoming",
  },
  {
    slug: "fancloud-denver-2026",
    title: "FanCloud Denver",
    city: "Denver",
    venue: "Colorado Convention Center",
    country: "USA",
    startDate: "2026-06-26",
    endDate: "2026-06-28",
    category: "Collectibles",
    eventType: "convention",
    color: "#f59e0b",
    heroImage: null,
    attendance: 60000,
    description:
      "Meet the athletes, wrestlers, and pop-culture personalities behind the most-wanted memorabilia of the year. Autograph alleys, photo ops, and intimate panels with the names that move the hobby.",
    ticketUrl: null,
    ticketOptions: standardTickets,
    celebrityName: null,
    celebrityBio: null,
    celebrityImage: null,
    featured: false,
    status: "upcoming",
  },
  {
    slug: "fancloud-chicago-2026",
    title: "FanCloud Chicago",
    city: "Chicago",
    venue: "McCormick Place",
    country: "USA",
    startDate: "2026-09-04",
    endDate: "2026-09-06",
    category: "Sci-Fi",
    eventType: "convention",
    color: "#db2777",
    heroImage: null,
    attendance: 70000,
    description:
      "Cast reunions from the franchises that built the genre. Live panels, photo ops on themed sets, and exclusive convention-only Q&As with sci-fi's most iconic actors and writers.",
    ticketUrl: null,
    ticketOptions: standardTickets,
    celebrityName: null,
    celebrityBio: null,
    celebrityImage: null,
    featured: false,
    status: "upcoming",
  },
  {
    slug: "fancloud-atlanta-horror-nights-2026",
    title: "FanCloud Atlanta Horror Nights",
    city: "Atlanta",
    venue: "Georgia World Congress Center",
    country: "USA",
    startDate: "2026-10-23",
    endDate: "2026-10-25",
    category: "Horror",
    eventType: "convention",
    color: "#111827",
    heroImage: null,
    attendance: 40000,
    description:
      "Scream queens, slasher icons, and FX legends — together for three nights. Photo ops on themed sets, autograph sessions, and after-dark Q&A panels with the actors who defined the genre.",
    ticketUrl: null,
    ticketOptions: standardTickets,
    celebrityName: null,
    celebrityBio: null,
    celebrityImage: null,
    featured: false,
    status: "upcoming",
  },
  {
    slug: "fancloud-seattle-gamecon-2026",
    title: "FanCloud Seattle GameCon",
    city: "Seattle",
    venue: "Seattle Convention Center",
    country: "USA",
    startDate: "2026-11-13",
    endDate: "2026-11-15",
    category: "Gaming",
    eventType: "convention",
    color: "#14b8a6",
    heroImage: null,
    attendance: 55000,
    description:
      "Esports stars, streamers, and the voice cast behind your favorite games — all on one floor. Meet-and-greets, photo ops, and live panels with the players and performers who built the scene.",
    ticketUrl: null,
    ticketOptions: [],
    celebrityName: null,
    celebrityBio: null,
    celebrityImage: null,
    featured: false,
    status: "upcoming",
  },
  {
    slug: "fancloud-london-2027",
    title: "FanCloud London",
    city: "London",
    venue: "ExCeL London",
    country: "UK",
    startDate: "2027-02-19",
    endDate: "2027-02-21",
    category: "Comic Con",
    eventType: "convention",
    color: "#2563eb",
    heroImage: null,
    attendance: 110000,
    description:
      "FANCLOUD's UK debut brings A-list cast reunions, exclusive European-only signings, and the biggest international celebrity lineup the UK has seen this season.",
    ticketUrl: null,
    ticketOptions: [],
    celebrityName: null,
    celebrityBio: null,
    celebrityImage: null,
    featured: false,
    status: "upcoming",
  },
  {
    slug: "fancloud-toronto-2027",
    title: "FanCloud Toronto",
    city: "Toronto",
    venue: "Metro Toronto Convention Centre",
    country: "Canada",
    startDate: "2027-03-19",
    endDate: "2027-03-21",
    category: "Comic Con",
    eventType: "convention",
    color: "#84cc16",
    heroImage: null,
    attendance: 130000,
    description:
      "North America's most-loved cast reunions return to Toronto. Three days of panels, photo ops, and autograph signings with the stars fans actually want to meet — and a few we're not allowed to announce yet.",
    ticketUrl: null,
    ticketOptions: [],
    celebrityName: null,
    celebrityBio: null,
    celebrityImage: null,
    featured: false,
    status: "upcoming",
  },
  {
    slug: "fancloud-austin-2026",
    title: "FanCloud Austin",
    city: "Austin",
    venue: "Austin Convention Center",
    country: "USA",
    startDate: "2026-03-06",
    endDate: "2026-03-08",
    category: "Gaming",
    eventType: "convention",
    color: "#f97316",
    heroImage: null,
    attendance: 48000,
    description:
      "A sold-out weekend of meet-and-greets with the voice actors, streamers, and creators behind the games you love. Thanks to everyone who lined up — the photo-op floor was packed all three days.",
    ticketUrl: null,
    ticketOptions: [],
    celebrityName: null,
    celebrityBio: null,
    celebrityImage: null,
    featured: false,
    status: "past",
  },
  {
    slug: "fancloud-miami-2026",
    title: "FanCloud Miami",
    city: "Miami",
    venue: "Miami Beach Convention Center",
    country: "USA",
    startDate: "2026-04-17",
    endDate: "2026-04-19",
    category: "Anime",
    eventType: "convention",
    color: "#a855f7",
    heroImage: null,
    attendance: 35000,
    description:
      "An unforgettable weekend of voice-actor Q&As, mangaka signings, and photo ops with anime's biggest international stars. We wrapped with a beachside cast meet-and-greet that's still in the group chats.",
    ticketUrl: null,
    ticketOptions: [],
    celebrityName: null,
    celebrityBio: null,
    celebrityImage: null,
    featured: false,
    status: "past",
  },
];
