import type { EventInput } from "./types";

type SeedEvent = EventInput & { slug: string };

export const seedEvents: SeedEvent[] = [
  {
    slug: "fancloud-los-angeles-2026",
    title: "FanCloud Los Angeles",
    city: "Los Angeles",
    venue: "Los Angeles Convention Center",
    country: "USA",
    startDate: "2026-07-10",
    endDate: "2026-07-12",
    category: "Comic Con",
    color: "#6d5efc",
    heroImage: null,
    attendance: 95000,
    description:
      "Three days of A-list reunions, photo ops, and live Q&A panels in downtown LA. Expect cast members from the biggest film and streaming franchises of the year, plus exclusive autograph sessions you won't get anywhere else.",
    ticketUrl: "https://example.com/tickets",
    featured: true,
    status: "upcoming",
  },
  {
    slug: "fancloud-new-york-2026",
    title: "FanCloud New York",
    city: "New York",
    venue: "Javits Center",
    country: "USA",
    startDate: "2026-10-08",
    endDate: "2026-10-11",
    category: "Comic Con",
    color: "#16a34a",
    heroImage: null,
    attendance: 180000,
    description:
      "Our flagship east-coast show packs four days of celebrity panels, autograph sessions, and exclusive photo ops with stars from film, TV, and animation. The biggest celebrity lineup on the calendar.",
    ticketUrl: "https://example.com/tickets",
    featured: true,
    status: "upcoming",
  },
  {
    slug: "fancloud-tokyo-anime-fest-2026",
    title: "FanCloud Tokyo Anime Fest",
    city: "Tokyo",
    venue: "Tokyo Big Sight",
    country: "Japan",
    startDate: "2026-08-21",
    endDate: "2026-08-23",
    category: "Anime",
    color: "#ec4899",
    heroImage: null,
    attendance: 120000,
    description:
      "Voice-actor stages, mangaka signings, and studio Q&As with the people behind your favorite anime. The largest international voice-talent lineup of the year, plus rare on-stage interviews and exclusive autograph sessions.",
    ticketUrl: "https://example.com/tickets",
    featured: true,
    status: "upcoming",
  },
  {
    slug: "fancloud-denver-2026",
    title: "FanCloud Denver",
    city: "Denver",
    venue: "Colorado Convention Center",
    country: "USA",
    startDate: "2026-06-26",
    endDate: "2026-06-28",
    category: "Collectibles",
    color: "#f59e0b",
    heroImage: null,
    attendance: 60000,
    description:
      "Meet the athletes, wrestlers, and pop-culture personalities behind the most-wanted memorabilia of the year. Autograph alleys, photo ops, and intimate panels with the names that move the hobby.",
    ticketUrl: "https://example.com/tickets",
    featured: false,
    status: "upcoming",
  },
  {
    slug: "fancloud-chicago-2026",
    title: "FanCloud Chicago",
    city: "Chicago",
    venue: "McCormick Place",
    country: "USA",
    startDate: "2026-09-04",
    endDate: "2026-09-06",
    category: "Sci-Fi",
    color: "#db2777",
    heroImage: null,
    attendance: 70000,
    description:
      "Cast reunions from the franchises that built the genre. Live panels, photo ops on themed sets, and exclusive convention-only Q&As with sci-fi's most iconic actors and writers.",
    ticketUrl: "https://example.com/tickets",
    featured: false,
    status: "upcoming",
  },
  {
    slug: "fancloud-atlanta-horror-nights-2026",
    title: "FanCloud Atlanta Horror Nights",
    city: "Atlanta",
    venue: "Georgia World Congress Center",
    country: "USA",
    startDate: "2026-10-23",
    endDate: "2026-10-25",
    category: "Horror",
    color: "#111827",
    heroImage: null,
    attendance: 40000,
    description:
      "Scream queens, slasher icons, and FX legends — together for three nights. Photo ops on themed sets, autograph sessions, and after-dark Q&A panels with the actors who defined the genre.",
    ticketUrl: "https://example.com/tickets",
    featured: false,
    status: "upcoming",
  },
  {
    slug: "fancloud-seattle-gamecon-2026",
    title: "FanCloud Seattle GameCon",
    city: "Seattle",
    venue: "Seattle Convention Center",
    country: "USA",
    startDate: "2026-11-13",
    endDate: "2026-11-15",
    category: "Gaming",
    color: "#14b8a6",
    heroImage: null,
    attendance: 55000,
    description:
      "Esports stars, streamers, and the voice cast behind your favorite games — all on one floor. Meet-and-greets, photo ops, and live panels with the players and performers who built the scene.",
    ticketUrl: null,
    featured: false,
    status: "upcoming",
  },
  {
    slug: "fancloud-london-2027",
    title: "FanCloud London",
    city: "London",
    venue: "ExCeL London",
    country: "UK",
    startDate: "2027-02-19",
    endDate: "2027-02-21",
    category: "Comic Con",
    color: "#2563eb",
    heroImage: null,
    attendance: 110000,
    description:
      "FANCLOUD's UK debut brings A-list cast reunions, exclusive European-only signings, and the biggest international celebrity lineup the UK has seen this season.",
    ticketUrl: null,
    featured: false,
    status: "upcoming",
  },
  {
    slug: "fancloud-toronto-2027",
    title: "FanCloud Toronto",
    city: "Toronto",
    venue: "Metro Toronto Convention Centre",
    country: "Canada",
    startDate: "2027-03-19",
    endDate: "2027-03-21",
    category: "Comic Con",
    color: "#84cc16",
    heroImage: null,
    attendance: 130000,
    description:
      "North America's most-loved cast reunions return to Toronto. Three days of panels, photo ops, and autograph signings with the stars fans actually want to meet — and a few we're not allowed to announce yet.",
    ticketUrl: null,
    featured: false,
    status: "upcoming",
  },
  {
    slug: "fancloud-austin-2026",
    title: "FanCloud Austin",
    city: "Austin",
    venue: "Austin Convention Center",
    country: "USA",
    startDate: "2026-03-06",
    endDate: "2026-03-08",
    category: "Gaming",
    color: "#f97316",
    heroImage: null,
    attendance: 48000,
    description:
      "A sold-out weekend of meet-and-greets with the voice actors, streamers, and creators behind the games you love. Thanks to everyone who lined up — the photo-op floor was packed all three days.",
    ticketUrl: null,
    featured: false,
    status: "past",
  },
  {
    slug: "fancloud-miami-2026",
    title: "FanCloud Miami",
    city: "Miami",
    venue: "Miami Beach Convention Center",
    country: "USA",
    startDate: "2026-04-17",
    endDate: "2026-04-19",
    category: "Anime",
    color: "#a855f7",
    heroImage: null,
    attendance: 35000,
    description:
      "An unforgettable weekend of voice-actor Q&As, mangaka signings, and photo ops with anime's biggest international stars. We wrapped with a beachside cast meet-and-greet that's still in the group chats.",
    ticketUrl: null,
    featured: false,
    status: "past",
  },
];
